title: Dylan Runkel
description: >
  Dylan Runkel
copyright: Untitled
sass:
  sass_dir: assets/sass
url: https://dylanrunkel.github.io
linkedin_username: "dylanrunkel"
github_username:  "drunkel"
stackoverflow_uid: "2324024"
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5
