title: Dylan Runkel
description: >
  Dylan Runkel
copyright: Untitled
sass:
  sass_dir: assets/sass
url: dylanrunkel.github.io
linkedin_username: "dylanrunkel"
github_username:  "drunkel"
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5
